title: decera - the decentralized era # name of the site
author: # name of site's author
email: hi@decera.ch # email of site's author
url: https://decera.ch # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  We believe in an open economy, digital money, peer-to-peer transactions and trustless applications on a global scale - all you need is an internet connection.
favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
